BEGIN;

CREATE SCHEMA IF NOT EXISTS cf_shadowglass_v8_warpspeed;

CREATE TABLE IF NOT EXISTS cf_shadowglass_v8_warpspeed.counties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    state TEXT,
    base_url TEXT NOT NULL,
    platform TEXT,
    is_active INTEGER,
    created_at TEXT
);

CREATE TABLE IF NOT EXISTS cf_shadowglass_v8_warpspeed.instrument_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    code INTEGER,
    created_at TEXT
);

CREATE TABLE IF NOT EXISTS cf_shadowglass_v8_warpspeed.deed_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id TEXT,
    county TEXT NOT NULL,
    instrument_type TEXT NOT NULL,
    instrument_type_id BIGINT,
    grantor TEXT,
    grantee TEXT,
    recorded_date TEXT,
    filing_date TEXT,
    legal_description TEXT,
    legal_normalized TEXT,
    section TEXT,
    block TEXT,
    book TEXT,
    page_num TEXT,
    volume TEXT,
    doc_number TEXT,
    consideration TEXT,
    source_url TEXT,
    r2_key TEXT,
    created_at TEXT
);

CREATE TABLE IF NOT EXISTS cf_shadowglass_v8_warpspeed.scrape_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    county_id BIGINT NOT NULL,
    instrument_type_id BIGINT NOT NULL,
    status TEXT,
    total_records INTEGER,
    scraped_records INTEGER,
    last_page INTEGER,
    started_at TEXT,
    completed_at TEXT,
    updated_at TEXT
);

CREATE TABLE IF NOT EXISTS cf_shadowglass_v8_warpspeed.scrape_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT,
    level TEXT,
    message TEXT,
    metadata TEXT,
    created_at TEXT
);

CREATE TABLE IF NOT EXISTS cf_shadowglass_v8_warpspeed.r2_uploads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    r2_key TEXT NOT NULL,
    county_id BIGINT,
    instrument_type_id BIGINT,
    page_number INTEGER,
    record_count INTEGER,
    uploaded_at TEXT
);

CREATE INDEX IF NOT EXISTS deed_records_county_idx
    ON cf_shadowglass_v8_warpspeed.deed_records (county);
CREATE INDEX IF NOT EXISTS deed_records_external_id_idx
    ON cf_shadowglass_v8_warpspeed.deed_records (external_id);
CREATE INDEX IF NOT EXISTS deed_records_recorded_date_idx
    ON cf_shadowglass_v8_warpspeed.deed_records (recorded_date);
CREATE INDEX IF NOT EXISTS scrape_logs_job_id_idx
    ON cf_shadowglass_v8_warpspeed.scrape_logs (job_id);
CREATE UNIQUE INDEX IF NOT EXISTS deed_records_identity_idx
    ON cf_shadowglass_v8_warpspeed.deed_records (county, instrument_type, external_id)
    WHERE external_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS scrape_jobs_instrument_idx
    ON cf_shadowglass_v8_warpspeed.scrape_jobs (county_id, instrument_type_id);
CREATE UNIQUE INDEX IF NOT EXISTS r2_uploads_key_idx
    ON cf_shadowglass_v8_warpspeed.r2_uploads (r2_key);

CREATE TABLE IF NOT EXISTS cf_shadowglass_v8_warpspeed.work_queue (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    job_kind TEXT NOT NULL,
    payload JSONB NOT NULL,
    payload_version SMALLINT NOT NULL DEFAULT 1,
    idempotency_key TEXT NOT NULL UNIQUE,
    state TEXT NOT NULL DEFAULT 'pending'
        CHECK (state IN ('pending', 'paused', 'processing', 'completed', 'dead')),
    priority INTEGER NOT NULL DEFAULT 100,
    available_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    max_attempts INTEGER NOT NULL DEFAULT 5 CHECK (max_attempts BETWEEN 1 AND 100),
    leased_by TEXT,
    lease_token UUID,
    lease_expires_at TIMESTAMPTZ,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    completed_at TIMESTAMPTZ,
    CHECK (
        (state = 'processing' AND leased_by IS NOT NULL AND lease_token IS NOT NULL
            AND lease_expires_at IS NOT NULL)
        OR state <> 'processing'
    )
);

CREATE INDEX IF NOT EXISTS work_queue_claim_idx
    ON cf_shadowglass_v8_warpspeed.work_queue (priority, available_at, id)
    WHERE state = 'pending';
CREATE INDEX IF NOT EXISTS work_queue_stale_lease_idx
    ON cf_shadowglass_v8_warpspeed.work_queue (lease_expires_at)
    WHERE state = 'processing';

CREATE TABLE IF NOT EXISTS cf_shadowglass_v8_warpspeed.work_queue_dead_letter (
    queue_id BIGINT PRIMARY KEY,
    job_kind TEXT NOT NULL,
    payload JSONB NOT NULL,
    payload_version SMALLINT NOT NULL,
    idempotency_key TEXT NOT NULL UNIQUE,
    attempts INTEGER NOT NULL,
    max_attempts INTEGER NOT NULL,
    last_error TEXT,
    failed_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE IF NOT EXISTS cf_shadowglass_v8_warpspeed.dedup_kv (
    scope TEXT NOT NULL,
    key TEXT NOT NULL,
    value BYTEA NOT NULL,
    source_etag TEXT,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (scope, key)
);

CREATE TABLE IF NOT EXISTS cf_shadowglass_v8_warpspeed.migration_receipts (
    source_kind TEXT NOT NULL,
    source_identity TEXT NOT NULL,
    source_sha256 TEXT NOT NULL,
    source_count BIGINT NOT NULL CHECK (source_count >= 0),
    target_count BIGINT NOT NULL CHECK (target_count >= 0),
    source_digest TEXT NOT NULL,
    target_digest TEXT NOT NULL,
    completed_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (source_kind, source_identity)
);

CREATE TABLE IF NOT EXISTS cf_shadowglass_v8_warpspeed.deployment_receipts (
    gate TEXT PRIMARY KEY,
    release_id TEXT NOT NULL,
    source_tree TEXT NOT NULL CHECK (source_tree ~ '^[0-9a-f]{40}$'),
    source_digest TEXT NOT NULL CHECK (source_digest ~ '^[0-9a-f]{64}$'),
    status TEXT NOT NULL CHECK (status IN ('passed', 'rolled_back')),
    evidence_sha256 TEXT NOT NULL CHECK (evidence_sha256 ~ '^[0-9a-f]{64}$'),
    occurred_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    details JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS cf_shadowglass_v8_warpspeed.deployment_events (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    attempt_id UUID NOT NULL,
    gate TEXT NOT NULL,
    release_id TEXT NOT NULL,
    source_tree TEXT NOT NULL CHECK (source_tree ~ '^[0-9a-f]{40}$'),
    source_digest TEXT NOT NULL CHECK (source_digest ~ '^[0-9a-f]{64}$'),
    status TEXT NOT NULL CHECK (status IN ('passed', 'rolled_back')),
    evidence_sha256 TEXT NOT NULL CHECK (evidence_sha256 ~ '^[0-9a-f]{64}$'),
    occurred_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);
ALTER TABLE cf_shadowglass_v8_warpspeed.deployment_receipts
    ADD COLUMN IF NOT EXISTS source_tree TEXT,
    ADD COLUMN IF NOT EXISTS source_digest TEXT,
    ADD COLUMN IF NOT EXISTS occurred_at TIMESTAMPTZ;
ALTER TABLE cf_shadowglass_v8_warpspeed.deployment_events
    ADD COLUMN IF NOT EXISTS source_tree TEXT,
    ADD COLUMN IF NOT EXISTS source_digest TEXT,
    ADD COLUMN IF NOT EXISTS occurred_at TIMESTAMPTZ;
CREATE UNIQUE INDEX IF NOT EXISTS deployment_events_attempt_gate_release_uidx
    ON cf_shadowglass_v8_warpspeed.deployment_events (attempt_id, gate, release_id);
CREATE INDEX IF NOT EXISTS deployment_events_release_gate_idx
    ON cf_shadowglass_v8_warpspeed.deployment_events (release_id, gate, id);

DO $grant$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cf_shadowglass_v8_warpspeed') THEN
        GRANT USAGE ON SCHEMA cf_shadowglass_v8_warpspeed TO cf_shadowglass_v8_warpspeed;
        REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER
          ON ALL TABLES IN SCHEMA cf_shadowglass_v8_warpspeed
          FROM cf_shadowglass_v8_warpspeed;
        REVOKE ALL ON ALL SEQUENCES IN SCHEMA cf_shadowglass_v8_warpspeed
          FROM cf_shadowglass_v8_warpspeed;
        GRANT SELECT ON
          cf_shadowglass_v8_warpspeed.counties,
          cf_shadowglass_v8_warpspeed.deed_records,
          cf_shadowglass_v8_warpspeed.instrument_types,
          cf_shadowglass_v8_warpspeed.r2_uploads,
          cf_shadowglass_v8_warpspeed.scrape_jobs,
          cf_shadowglass_v8_warpspeed.scrape_logs,
          cf_shadowglass_v8_warpspeed.work_queue
          TO cf_shadowglass_v8_warpspeed;
        GRANT INSERT ON cf_shadowglass_v8_warpspeed.work_queue
          TO cf_shadowglass_v8_warpspeed;
        GRANT UPDATE (state, updated_at)
          ON cf_shadowglass_v8_warpspeed.work_queue
          TO cf_shadowglass_v8_warpspeed;
        GRANT USAGE, SELECT, UPDATE ON SEQUENCE
          cf_shadowglass_v8_warpspeed.work_queue_id_seq
          TO cf_shadowglass_v8_warpspeed;
        REVOKE INSERT, UPDATE, DELETE ON
          cf_shadowglass_v8_warpspeed.migration_receipts,
          cf_shadowglass_v8_warpspeed.deployment_receipts,
          cf_shadowglass_v8_warpspeed.deployment_events
          FROM cf_shadowglass_v8_warpspeed;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cf_shadowglass_v8_warpspeed_migrator') THEN
        GRANT USAGE ON SCHEMA cf_shadowglass_v8_warpspeed
          TO cf_shadowglass_v8_warpspeed_migrator;
        GRANT SELECT, INSERT, UPDATE ON
          cf_shadowglass_v8_warpspeed.counties,
          cf_shadowglass_v8_warpspeed.deed_records,
          cf_shadowglass_v8_warpspeed.instrument_types,
          cf_shadowglass_v8_warpspeed.r2_uploads,
          cf_shadowglass_v8_warpspeed.scrape_jobs,
          cf_shadowglass_v8_warpspeed.scrape_logs,
          cf_shadowglass_v8_warpspeed.dedup_kv,
          cf_shadowglass_v8_warpspeed.migration_receipts
          TO cf_shadowglass_v8_warpspeed_migrator;
        GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA cf_shadowglass_v8_warpspeed
          TO cf_shadowglass_v8_warpspeed_migrator;
        REVOKE ALL ON
          cf_shadowglass_v8_warpspeed.deployment_receipts,
          cf_shadowglass_v8_warpspeed.deployment_events
          FROM cf_shadowglass_v8_warpspeed_migrator;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cf_shadowglass_v8_warpspeed_consumer') THEN
        GRANT USAGE ON SCHEMA cf_shadowglass_v8_warpspeed
          TO cf_shadowglass_v8_warpspeed_consumer;
        GRANT SELECT ON ALL TABLES IN SCHEMA cf_shadowglass_v8_warpspeed
          TO cf_shadowglass_v8_warpspeed_consumer;
        GRANT INSERT, UPDATE ON
          cf_shadowglass_v8_warpspeed.work_queue,
          cf_shadowglass_v8_warpspeed.work_queue_dead_letter,
          cf_shadowglass_v8_warpspeed.deed_records,
          cf_shadowglass_v8_warpspeed.scrape_jobs,
          cf_shadowglass_v8_warpspeed.scrape_logs,
          cf_shadowglass_v8_warpspeed.r2_uploads,
          cf_shadowglass_v8_warpspeed.dedup_kv
          TO cf_shadowglass_v8_warpspeed_consumer;
        GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA cf_shadowglass_v8_warpspeed
          TO cf_shadowglass_v8_warpspeed_consumer;
        REVOKE ALL ON
          cf_shadowglass_v8_warpspeed.migration_receipts,
          cf_shadowglass_v8_warpspeed.deployment_receipts,
          cf_shadowglass_v8_warpspeed.deployment_events
          FROM cf_shadowglass_v8_warpspeed_consumer;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cf_shadowglass_v8_warpspeed_scheduler') THEN
        GRANT USAGE ON SCHEMA cf_shadowglass_v8_warpspeed
          TO cf_shadowglass_v8_warpspeed_scheduler;
        GRANT SELECT ON
          cf_shadowglass_v8_warpspeed.counties,
          cf_shadowglass_v8_warpspeed.instrument_types,
          cf_shadowglass_v8_warpspeed.work_queue
          TO cf_shadowglass_v8_warpspeed_scheduler;
        GRANT INSERT ON cf_shadowglass_v8_warpspeed.work_queue
          TO cf_shadowglass_v8_warpspeed_scheduler;
        GRANT USAGE, SELECT, UPDATE ON SEQUENCE
          cf_shadowglass_v8_warpspeed.work_queue_id_seq
          TO cf_shadowglass_v8_warpspeed_scheduler;
        REVOKE ALL ON
          cf_shadowglass_v8_warpspeed.deed_records,
          cf_shadowglass_v8_warpspeed.scrape_jobs,
          cf_shadowglass_v8_warpspeed.scrape_logs,
          cf_shadowglass_v8_warpspeed.r2_uploads,
          cf_shadowglass_v8_warpspeed.dedup_kv,
          cf_shadowglass_v8_warpspeed.migration_receipts,
          cf_shadowglass_v8_warpspeed.deployment_receipts,
          cf_shadowglass_v8_warpspeed.deployment_events
          FROM cf_shadowglass_v8_warpspeed_scheduler;
    END IF;
END
$grant$;

COMMIT;
